#!/usr/bin/env bash

set -e

rails-app-starter() {
  run="run --rm --remove-orphans"
  rails_prod_profile="docker compose --profile rails-production"
  rails="$rails_prod_profile $run rails-production-server"

  # Build the containers
  $rails_prod_profile build
  # Install gems
  $rails bundle install
  # Precompile assets
  $rails_prod_profile $run rails-production-assets-precompile
  # Create the database
  $rails rails db:create
  # Migrate the database
  $rails rails db:migrate
  # Start the production server
  $rails_prod_profile up -d
}

rails-app-starter
