#!/usr/bin/env bash

set -e

dcp="docker compose --profile"
run="run -it --rm"
production="$dcp rails-production"
runner="$production $run rails-production-server"

echo "# Build the containers"
$production build
echo "# Install gems"
#$runner gem install "bundler:2.4.19"
$runner bundle install
echo "# Create the database"
$runner rails db:create
echo "# Migrate the database"
$runner rails db:migrate
echo "# Start the project"
$production up -d
