x-production-env: &rails-production-env
  env_file:
    - .env
  environment:
    - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rails-production-db
    - RACK_ENV=production
    - RAILS_ENV=production
    - RAILS_LOG_TO_STDOUT=enabled
    - REDIS_URL=redis://rails-production-redis-actioncable:6379/1
    - REDIS_URL_2=redis://rails-production-redis-sidekiq:6379/1
    - SECRET_KEY_BASE
    - VIRTUAL_HOST
    - VIRTUAL_PORT

x-development-env: &rails-development-env
  env_file:
    - .env
  environment:
    - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rails-development-db
    - RACK_ENV=development
    - RAILS_ENV=development
    - RAILS_LOG_TO_STDOUT=enabled
    - REDIS_URL=redis://rails-development-redis-actioncable:6379/1
    - REDIS_URL_2=redis://rails-development-redis-sidekiq:6379/1
    - SECRET_KEY_BASE
    - VIRTUAL_HOST
    - VIRTUAL_PORT

x-javascript-development-server-env: &javascript-development-server-env
  environment:
    - HOST=0.0.0.0
    - PORT=${VIRTUAL_PORT}
    - REACT_APP_API_URL=https://dev-api-${VIRTUAL_HOST}
    - WDS_SOCKET_PORT=443

x-rails-server-src-volumes: &rails-server-src-volumes
  volumes:
    - jasonben_ide_bundle:/jasonben/ide/bundle
    - src:/jasonben/ide/code/src
  working_dir: /jasonben/ide/code/src/server

x-javascript-client-src: &javascript-client-src
  volumes:
    - src:/jasonben/ide/src
  working_dir: /jasonben/ide/src/client

x-redis: &redis-base
  image: redis:7.0.5-alpine3.16
  command: redis-server
  restart: always

x-base-development-image: &base-development-image
  user: "1000:1000"
  image: jasonben/ide:latest

x-rails-production-image: &rails-production-image
  user: "1000:1000"
  build:
    context: .
    dockerfile: Dockerfile
  image: jasonben/rails-app-starter

x-rails-production-image-with-env: &rails-production-image-with-env
  <<: [*rails-production-image, *rails-production-env]
  working_dir: /jasonben/ide/code/src/server

services:
  rails-production-server:
    profiles:
      - rails-production
    <<: [*rails-server-src-volumes, *rails-production-image-with-env]
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rails-production-server.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rails-production-server.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rails-production-server.rule=Host(`api-${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-rails-production-server.loadbalancer.server.port=${VIRTUAL_PORT}"
    networks:
      - public-web
      - rails-production
    depends_on:
      - rails-production-db
      - rails-production-redis-actioncable
    command: bundle exec puma -C config/puma.rb -p ${VIRTUAL_PORT} -b tcp://0.0.0.0

  rails-production-db:
    profiles:
      - rails-production
    image: postgres:14.4-alpine3.16
    restart: always
    networks:
      - rails-production
    volumes:
      - rails-production-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data

  rails-production-sidekiq:
    profiles:
      - rails-production
    image: jasonben/rails-app-starter
    depends_on:
      - rails-production-redis-sidekiq
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rails-production-db
      - REDIS_URL=redis://rails-production-redis-sidekiq:6379/1
      - REDIS_PROVIDER=REDIS_URL
      - RAILS_ENV=production
      - RACK_ENV=production
      - RAILS_LOG_TO_STDOUT=enabled
    restart: always
    networks:
      - rails-production
    working_dir: /jasonben/ide/code/src/server
    command: sh -c "bundle exec sidekiq"

  rails-production-redis-actioncable:
    profiles:
      - rails-production
    <<: *redis-base
    networks:
      - rails-production

  rails-production-redis-sidekiq:
    profiles:
      - rails-production
    <<: *redis-base
    networks:
      - rails-production

  html-production-server:
    profiles:
      - rails-production
    restart: always
    image: nginx:1.23.1-alpine
    <<: *javascript-client-src
    networks:
      - public-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-nginx.rule=Host(`html-${VIRTUAL_HOST}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-nginx.loadbalancer.server.port=80"
    command: /bin/sh -c "exec nginx -g 'daemon off;'"

  rails-development-server:
    profiles:
      - rails-development
    <<: [*base-development-image, *rails-development-env, *rails-server-src-volumes]
    depends_on:
      - rails-development-db
      - rails-development-redis-actioncable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rails-development-server.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rails-development-server.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-rails-development-server.loadbalancer.server.port=${VIRTUAL_PORT:-3000}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-rails-development-server.rule=Host(`dev-api-${VIRTUAL_HOST}`)"
    networks:
      - public-web
      - rails-development
    command: bundle exec puma -C config/puma.rb -p "${VIRTUAL_PORT}" -b tcp://0.0.0.0

  rails-development-db: &rails-development-db
    profiles:
      - ide
      - rails-development
    image: postgres:14.4-alpine3.16
    networks:
      - rails-development
    volumes:
      - rails-development-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data

  rails-test-db:
    profiles:
      - rails-development
      - ide
    <<: *rails-development-db
    volumes:
      - rails-test-db-data:/var/lib/postgresql/data

  rails-development-sidekiq:
    profiles:
      - rails-development
    <<: *base-development-image
    depends_on:
      - rails-development-db
      - rails-development-redis-sidekiq
    networks:
      - rails-development
    volumes:
      - jasonben_ide_bundle:/jasonben/ide/bundle
    command: ["bundle", "exec", "sidekiq"]

  rails-development-redis-actioncable:
    profiles:
      - rails-development
    <<: *redis-base
    networks:
      - rails-development

  rails-development-redis-sidekiq:
    profiles:
      - rails-development
    <<: *redis-base
    networks:
      - rails-development

  javascript-development-server:
    profiles:
      - javascript-development
    <<: [*base-development-image, *javascript-client-src, *javascript-development-server-env]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-javascript-development-server.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-javascript-development-server.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-javascript-development-server.loadbalancer.server.port=${VIRTUAL_PORT}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-javascript-development-server.rule=Host(`dev-${VIRTUAL_HOST}`)"
    networks:
      - public-web
    command: yarn start

  yarn:
    <<: [*base-development-image, *javascript-client-src]
    profiles:
      - dev
    entrypoint:
      - yarn

  create-rails-app:
    <<: [*base-development-image, *rails-server-src-volumes]
    tty: true
    profiles:
      - init
    command: sh -c "gem install rails && rails new -d postgresql --skip-git --skip-bundle ."

  jumpstart-rails:
    <<: [*base-development-image, *rails-server-src-volumes]
    tty: true
    environment:
      - SKIP_GIT=1
    profiles:
      - jumpstart-rails
    command: sh -c "gem install rails && rails new . -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb"

  create-react-app:
    <<: [*base-development-image, *javascript-client-src]
    tty: true
    profiles:
      - init
    command: sh -c "rm -rf .keep && npx --yes create-react-app ."

  build-react-app:
    <<: [*base-development-image, *javascript-client-src]
    profiles:
      - dev
    environment:
      - REACT_APP_API_URL=https://api-${VIRTUAL_HOST}
    command: yarn run build

  # rails-production-assets-precompile:
  #   profiles:
  #     - rails-production
  #   <<: *rails-production-image-with-env
  #   networks:
  #     - rails-production
  #   volumes:
  #     - rails-production-ruby-public-assets:/jasonben/ide/code/src/server/public/assets
  #   user: "root"
  #   command: sh -c "chown -R ${IDE_USER}:${IDE_USER} /jasonben/ide/code/src/server/public/assets && bundle exec rails assets:precompile"

  ide: &ide
    profiles:
      - ide
      - rails-development
    tty: true
    <<: [*base-development-image]
    depends_on:
      - rails-development-db
      - rails-test-db
    environment:
      - DOCKER_HOST=tcp://dockersock:2375
      - VIRTUAL_HOST
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@rails-development-db
      - RAILS_ENV=development
    networks:
      - rails-production
      - rails-development
      - dockersock
    volumes:
      - jasonben_ide_bundle:/jasonben/ide/bundle
      - src:/jasonben/ide/code/src
      - solargraph-cache:/jasonben/ide/.solargraph
    working_dir: /jasonben/ide/code/src/server
    command: tmux new-session -A -s ide

  rails-app-starter-src:
    image: jasonben/rails-app-starter
    volumes:
      - src:/jasonben/ide/code/src
    working_dir: /jasonben/ide/code/src/server
    command: ["tail", "-f", "/dev/null"]

volumes:
  src:
    external: true
    name: rails-app-starter
  rails-production-ruby-public-assets:
  rails-development-db-data:
  rails-test-db-data:
  rails-production-db-data:
  solargraph-cache:
    external: true
  jasonben_ide_bundle:
    external: true

networks:
  dockersock:
    external: true
  public-web:
    name: webproxy
  rails-production:
    internal: true
  rails-development:
    internal: true
